# .github/workflows/build-windows.yml
name: Build exportchart.exe

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build exe with PyInstaller
      run: |
        pyinstaller --clean --onefile --windowed \
          --icon icon.ico \
          --add-data "chart_topcoin.db;." \
          exportchart.py

    - name: Upload built exe as artifact
      uses: actions/upload-artifact@v3
      with:
        name: exportchart-windows
        path: dist/exportchart.exe
